### ISSUE TITLE
Add custom properties to INDEXED_PROPERTIES

### ISSUE THREAD

**Issue by codediodeio** [oncletom/hexo-algolia#28]
Enhancement. The ability to add custom properties to the index. 

```
algolia:
  applicationID: 'ID'
  apiKey: 'Key'
  indexName: 'index'
  properties:
    - featured_image
    - something_else
```
