### ISSUE TITLE
hexo algolia error

### ISSUE THREAD

**Issue by Baikeryoyo** [oncletom/hexo-algolia#46]
![image](https://user-images.githubusercontent.com/57838797/129537864-c7cd46d5-4fa3-4bb7-8cf9-88efb672642e.png)

**Comment by thom4parisot** [comment]
Hi, I think you are referring to https://www.npmjs.com/package/hexo-algoliasearch, which is a different plugin.

Can you create it, again, on https://github.com/LouisBarranqueiro/hexo-algoliasearch/issues/new?

Thanks

**Comment by freemankevin** [comment]
@Baikeryoyo 

The authentication information should be added to the site's configuration file（`_config.yml`） instead of the theme's configuration file（`_config.yml`）. You can try it.


```yml
algolia:
  applicationID: 'applicationID'
  apiKey: 'apiKey' # only search apikey
  indexName: '...' 
```
